import type { AdminProduct } from '../../domain/admin-product/admin-product.model';

export const ADMIN_PRODUCT_SEED: AdminProduct[] = [
  {
    id: 'p-1',
    name: 'Leche Santa Clara',
    category: 'donas',
    priceMx: 15,
    status: 'active',
    collaboratorName: 'Mariana López',
    salesCount: 87,
    icon: 'milk-bottle',
  },
  {
    id: 'p-2',
    name: 'Fresa Cremosa',
    category: 'donas',
    priceMx: 18,
    status: 'active',
    collaboratorName: 'Mariana López',
    salesCount: 64,
    icon: 'donut',
  },
  {
    id: 'p-3',
    name: 'Cookie Choco Chips',
    category: 'galletas',
    priceMx: 22,
    status: 'out_of_stock',
    collaboratorName: 'Luis Ortega',
    salesCount: 120,
    icon: 'cookie',
  },
  {
    id: 'p-4',
    name: 'Glaseada Rosa',
    category: 'donas',
    priceMx: 17,
    status: 'active',
    collaboratorName: 'Mariana López',
    salesCount: 52,
    icon: 'donut',
  },
  {
    id: 'p-5',
    name: 'Frappe de Vainilla',
    category: 'bebidas',
    priceMx: 55,
    status: 'active',
    collaboratorName: 'Ana Ruiz',
    salesCount: 41,
    icon: 'milk-bottle',
  },
  {
    id: 'p-6',
    name: 'Iced Latte',
    category: 'bebidas',
    priceMx: 48,
    status: 'active',
    collaboratorName: 'Ana Ruiz',
    salesCount: 33,
    icon: 'milk-bottle',
  },
  {
    id: 'p-7',
    name: 'Avena y Miel',
    category: 'galletas',
    priceMx: 20,
    status: 'active',
    collaboratorName: 'Luis Ortega',
    salesCount: 28,
    icon: 'cookie',
  },
  {
    id: 'p-8',
    name: 'Dona Boston',
    category: 'donas',
    priceMx: 19,
    status: 'active',
    collaboratorName: 'Carla Méndez',
    salesCount: 71,
    icon: 'donut',
  },
  {
    id: 'p-9',
    name: 'Smoothie Mango',
    category: 'bebidas',
    priceMx: 52,
    status: 'out_of_stock',
    collaboratorName: 'Ana Ruiz',
    salesCount: 19,
    icon: 'milk-bottle',
  },
  {
    id: 'p-10',
    name: 'Galleta Red Velvet',
    category: 'galletas',
    priceMx: 24,
    status: 'active',
    collaboratorName: 'Luis Ortega',
    salesCount: 45,
    icon: 'cookie',
  },
  {
    id: 'p-11',
    name: 'Dona Chocolate Belga',
    category: 'donas',
    priceMx: 21,
    status: 'active',
    collaboratorName: 'Carla Méndez',
    salesCount: 93,
    icon: 'donut',
  },
  {
    id: 'p-12',
    name: 'Agua de Horchata',
    category: 'bebidas',
    priceMx: 35,
    status: 'active',
    collaboratorName: 'Ana Ruiz',
    salesCount: 22,
    icon: 'milk-bottle',
  },
  {
    id: 'p-13',
    name: 'Mini Donas (6 pzas)',
    category: 'donas',
    priceMx: 90,
    status: 'active',
    collaboratorName: 'Mariana López',
    salesCount: 15,
    icon: 'donut',
  },
  {
    id: 'p-14',
    name: 'Galleta de Avena',
    category: 'galletas',
    priceMx: 18,
    status: 'active',
    collaboratorName: 'Luis Ortega',
    salesCount: 36,
    icon: 'cookie',
  },
];
